// Agent <-> control plane channel. Every RPC here requires mTLS; the agent's
// identity is ALWAYS taken from the client certificate URI SAN
// (polarbeam://agent/<uuid>) and never from message fields.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: polarbeam/v1/agent.proto

package polarbeamv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_StreamConfig_FullMethodName = "/polarbeam.v1.AgentService/StreamConfig"
	AgentService_PushResults_FullMethodName  = "/polarbeam.v1.AgentService/PushResults"
	AgentService_RenewCert_FullMethodName    = "/polarbeam.v1.AgentService/RenewCert"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	// Long-lived stream: the server pushes FULL config snapshots (never
	// diffs); the agent diffs locally against its running workers. The open
	// stream doubles as agent liveness.
	StreamConfig(ctx context.Context, in *AgentHello, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigSnapshot], error)
	// Batched result ingestion. Results may arrive late and out of order
	// (disk spool replay after an outage); the server orders by started_at.
	PushResults(ctx context.Context, in *PushResultsRequest, opts ...grpc.CallOption) (*PushResultsResponse, error)
	// Certificate rotation over the existing mTLS channel (CSR in, cert out).
	RenewCert(ctx context.Context, in *RenewCertRequest, opts ...grpc.CallOption) (*RenewCertResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) StreamConfig(ctx context.Context, in *AgentHello, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_StreamConfig_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentHello, ConfigSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamConfigClient = grpc.ServerStreamingClient[ConfigSnapshot]

func (c *agentServiceClient) PushResults(ctx context.Context, in *PushResultsRequest, opts ...grpc.CallOption) (*PushResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushResultsResponse)
	err := c.cc.Invoke(ctx, AgentService_PushResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RenewCert(ctx context.Context, in *RenewCertRequest, opts ...grpc.CallOption) (*RenewCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewCertResponse)
	err := c.cc.Invoke(ctx, AgentService_RenewCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	// Long-lived stream: the server pushes FULL config snapshots (never
	// diffs); the agent diffs locally against its running workers. The open
	// stream doubles as agent liveness.
	StreamConfig(*AgentHello, grpc.ServerStreamingServer[ConfigSnapshot]) error
	// Batched result ingestion. Results may arrive late and out of order
	// (disk spool replay after an outage); the server orders by started_at.
	PushResults(context.Context, *PushResultsRequest) (*PushResultsResponse, error)
	// Certificate rotation over the existing mTLS channel (CSR in, cert out).
	RenewCert(context.Context, *RenewCertRequest) (*RenewCertResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) StreamConfig(*AgentHello, grpc.ServerStreamingServer[ConfigSnapshot]) error {
	return status.Error(codes.Unimplemented, "method StreamConfig not implemented")
}
func (UnimplementedAgentServiceServer) PushResults(context.Context, *PushResultsRequest) (*PushResultsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushResults not implemented")
}
func (UnimplementedAgentServiceServer) RenewCert(context.Context, *RenewCertRequest) (*RenewCertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewCert not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_StreamConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AgentHello)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).StreamConfig(m, &grpc.GenericServerStream[AgentHello, ConfigSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamConfigServer = grpc.ServerStreamingServer[ConfigSnapshot]

func _AgentService_PushResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PushResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_PushResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PushResults(ctx, req.(*PushResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RenewCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RenewCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RenewCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RenewCert(ctx, req.(*RenewCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "polarbeam.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushResults",
			Handler:    _AgentService_PushResults_Handler,
		},
		{
			MethodName: "RenewCert",
			Handler:    _AgentService_RenewCert_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamConfig",
			Handler:       _AgentService_StreamConfig_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "polarbeam/v1/agent.proto",
}
