// Agent <-> control plane channel. Every RPC here requires mTLS; the agent's
// identity is ALWAYS taken from the client certificate URI SAN
// (polarbeam://agent/<uuid>) and never from message fields.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: polarbeam/v1/agent.proto

package polarbeamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentHello struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// Hash of the config snapshot the agent is currently running; lets the
	// server skip a no-op initial push.
	ConfigHash    string `protobuf:"bytes,2,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_polarbeam_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_polarbeam_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_polarbeam_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentHello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentHello) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

type ConfigSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content hash of the snapshot (server-computed, stable for identical
	// configs).
	ConfigHash    string       `protobuf:"bytes,1,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	Probes        []*ProbeSpec `protobuf:"bytes,2,rep,name=probes,proto3" json:"probes,omitempty"`
	Spool         *SpoolPolicy `protobuf:"bytes,3,opt,name=spool,proto3" json:"spool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSnapshot) Reset() {
	*x = ConfigSnapshot{}
	mi := &file_polarbeam_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSnapshot) ProtoMessage() {}

func (x *ConfigSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_polarbeam_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSnapshot.ProtoReflect.Descriptor instead.
func (*ConfigSnapshot) Descriptor() ([]byte, []int) {
	return file_polarbeam_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigSnapshot) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *ConfigSnapshot) GetProbes() []*ProbeSpec {
	if x != nil {
		return x.Probes
	}
	return nil
}

func (x *ConfigSnapshot) GetSpool() *SpoolPolicy {
	if x != nil {
		return x.Spool
	}
	return nil
}

// Server-tunable spool bounds (agent-local config takes precedence if set).
type SpoolPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxBytes      int64                  `protobuf:"varint,1,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	MaxAgeSeconds int64                  `protobuf:"varint,2,opt,name=max_age_seconds,json=maxAgeSeconds,proto3" json:"max_age_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpoolPolicy) Reset() {
	*x = SpoolPolicy{}
	mi := &file_polarbeam_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpoolPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpoolPolicy) ProtoMessage() {}

func (x *SpoolPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_polarbeam_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpoolPolicy.ProtoReflect.Descriptor instead.
func (*SpoolPolicy) Descriptor() ([]byte, []int) {
	return file_polarbeam_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *SpoolPolicy) GetMaxBytes() int64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

func (x *SpoolPolicy) GetMaxAgeSeconds() int64 {
	if x != nil {
		return x.MaxAgeSeconds
	}
	return 0
}

type PushResultsRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Results []*ProbeResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// Number of results dropped from the spool (overflow/age) since the last
	// acknowledged push — loss is reported, never silent. Legacy: pre-v0.4
	// servers only read this delta, and a retried push can double-count it.
	// Servers that understand dropped_total ignore this field when that one
	// is present.
	DroppedSinceLastPush uint64 `protobuf:"varint,2,opt,name=dropped_since_last_push,json=droppedSinceLastPush,proto3" json:"dropped_since_last_push,omitempty"`
	// Lifetime total of results this agent has dropped (monotonic except on
	// spool-state loss). Presence marks a total-reporting agent; the server
	// derives an idempotent delta from it, so retries never double-count.
	// Agents set BOTH fields to keep pre-v0.4 servers working.
	DroppedTotal  *uint64 `protobuf:"varint,3,opt,name=dropped_total,json=droppedTotal,proto3,oneof" json:"dropped_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResultsRequest) Reset() {
	*x = PushResultsRequest{}
	mi := &file_polarbeam_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResultsRequest) ProtoMessage() {}

func (x *PushResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polarbeam_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResultsRequest.ProtoReflect.Descriptor instead.
func (*PushResultsRequest) Descriptor() ([]byte, []int) {
	return file_polarbeam_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *PushResultsRequest) GetResults() []*ProbeResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *PushResultsRequest) GetDroppedSinceLastPush() uint64 {
	if x != nil {
		return x.DroppedSinceLastPush
	}
	return 0
}

func (x *PushResultsRequest) GetDroppedTotal() uint64 {
	if x != nil && x.DroppedTotal != nil {
		return *x.DroppedTotal
	}
	return 0
}

type PushResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      uint32                 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResultsResponse) Reset() {
	*x = PushResultsResponse{}
	mi := &file_polarbeam_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResultsResponse) ProtoMessage() {}

func (x *PushResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polarbeam_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResultsResponse.ProtoReflect.Descriptor instead.
func (*PushResultsResponse) Descriptor() ([]byte, []int) {
	return file_polarbeam_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PushResultsResponse) GetAccepted() uint32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

type RenewCertRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PKCS#10 CSR, DER (fresh key allowed; identity comes from the current
	// client certificate, not the CSR subject).
	CsrDer        []byte `protobuf:"bytes,1,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewCertRequest) Reset() {
	*x = RenewCertRequest{}
	mi := &file_polarbeam_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertRequest) ProtoMessage() {}

func (x *RenewCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polarbeam_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertRequest.ProtoReflect.Descriptor instead.
func (*RenewCertRequest) Descriptor() ([]byte, []int) {
	return file_polarbeam_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *RenewCertRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

type RenewCertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertDer       []byte                 `protobuf:"bytes,1,opt,name=cert_der,json=certDer,proto3" json:"cert_der,omitempty"`
	CaBundleDer   []byte                 `protobuf:"bytes,2,opt,name=ca_bundle_der,json=caBundleDer,proto3" json:"ca_bundle_der,omitempty"`
	NotAfter      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewCertResponse) Reset() {
	*x = RenewCertResponse{}
	mi := &file_polarbeam_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertResponse) ProtoMessage() {}

func (x *RenewCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polarbeam_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertResponse.ProtoReflect.Descriptor instead.
func (*RenewCertResponse) Descriptor() ([]byte, []int) {
	return file_polarbeam_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *RenewCertResponse) GetCertDer() []byte {
	if x != nil {
		return x.CertDer
	}
	return nil
}

func (x *RenewCertResponse) GetCaBundleDer() []byte {
	if x != nil {
		return x.CaBundleDer
	}
	return nil
}

func (x *RenewCertResponse) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

var File_polarbeam_v1_agent_proto protoreflect.FileDescriptor

const file_polarbeam_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x18polarbeam/v1/agent.proto\x12\fpolarbeam.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19polarbeam/v1/common.proto\"R\n" +
	"\n" +
	"AgentHello\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12\x1f\n" +
	"\vconfig_hash\x18\x02 \x01(\tR\n" +
	"configHash\"\x93\x01\n" +
	"\x0eConfigSnapshot\x12\x1f\n" +
	"\vconfig_hash\x18\x01 \x01(\tR\n" +
	"configHash\x12/\n" +
	"\x06probes\x18\x02 \x03(\v2\x17.polarbeam.v1.ProbeSpecR\x06probes\x12/\n" +
	"\x05spool\x18\x03 \x01(\v2\x19.polarbeam.v1.SpoolPolicyR\x05spool\"R\n" +
	"\vSpoolPolicy\x12\x1b\n" +
	"\tmax_bytes\x18\x01 \x01(\x03R\bmaxBytes\x12&\n" +
	"\x0fmax_age_seconds\x18\x02 \x01(\x03R\rmaxAgeSeconds\"\xbc\x01\n" +
	"\x12PushResultsRequest\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.polarbeam.v1.ProbeResultR\aresults\x125\n" +
	"\x17dropped_since_last_push\x18\x02 \x01(\x04R\x14droppedSinceLastPush\x12(\n" +
	"\rdropped_total\x18\x03 \x01(\x04H\x00R\fdroppedTotal\x88\x01\x01B\x10\n" +
	"\x0e_dropped_total\"1\n" +
	"\x13PushResultsResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\rR\baccepted\"+\n" +
	"\x10RenewCertRequest\x12\x17\n" +
	"\acsr_der\x18\x01 \x01(\fR\x06csrDer\"\x8b\x01\n" +
	"\x11RenewCertResponse\x12\x19\n" +
	"\bcert_der\x18\x01 \x01(\fR\acertDer\x12\"\n" +
	"\rca_bundle_der\x18\x02 \x01(\fR\vcaBundleDer\x127\n" +
	"\tnot_after\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter2\xfa\x01\n" +
	"\fAgentService\x12H\n" +
	"\fStreamConfig\x12\x18.polarbeam.v1.AgentHello\x1a\x1c.polarbeam.v1.ConfigSnapshot0\x01\x12R\n" +
	"\vPushResults\x12 .polarbeam.v1.PushResultsRequest\x1a!.polarbeam.v1.PushResultsResponse\x12L\n" +
	"\tRenewCert\x12\x1e.polarbeam.v1.RenewCertRequest\x1a\x1f.polarbeam.v1.RenewCertResponseB9Z7github.com/devalexllc/polarbeam/internal/pb/polarbeamv1b\x06proto3"

var (
	file_polarbeam_v1_agent_proto_rawDescOnce sync.Once
	file_polarbeam_v1_agent_proto_rawDescData []byte
)

func file_polarbeam_v1_agent_proto_rawDescGZIP() []byte {
	file_polarbeam_v1_agent_proto_rawDescOnce.Do(func() {
		file_polarbeam_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polarbeam_v1_agent_proto_rawDesc), len(file_polarbeam_v1_agent_proto_rawDesc)))
	})
	return file_polarbeam_v1_agent_proto_rawDescData
}

var file_polarbeam_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_polarbeam_v1_agent_proto_goTypes = []any{
	(*AgentHello)(nil),            // 0: polarbeam.v1.AgentHello
	(*ConfigSnapshot)(nil),        // 1: polarbeam.v1.ConfigSnapshot
	(*SpoolPolicy)(nil),           // 2: polarbeam.v1.SpoolPolicy
	(*PushResultsRequest)(nil),    // 3: polarbeam.v1.PushResultsRequest
	(*PushResultsResponse)(nil),   // 4: polarbeam.v1.PushResultsResponse
	(*RenewCertRequest)(nil),      // 5: polarbeam.v1.RenewCertRequest
	(*RenewCertResponse)(nil),     // 6: polarbeam.v1.RenewCertResponse
	(*ProbeSpec)(nil),             // 7: polarbeam.v1.ProbeSpec
	(*ProbeResult)(nil),           // 8: polarbeam.v1.ProbeResult
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_polarbeam_v1_agent_proto_depIdxs = []int32{
	7, // 0: polarbeam.v1.ConfigSnapshot.probes:type_name -> polarbeam.v1.ProbeSpec
	2, // 1: polarbeam.v1.ConfigSnapshot.spool:type_name -> polarbeam.v1.SpoolPolicy
	8, // 2: polarbeam.v1.PushResultsRequest.results:type_name -> polarbeam.v1.ProbeResult
	9, // 3: polarbeam.v1.RenewCertResponse.not_after:type_name -> google.protobuf.Timestamp
	0, // 4: polarbeam.v1.AgentService.StreamConfig:input_type -> polarbeam.v1.AgentHello
	3, // 5: polarbeam.v1.AgentService.PushResults:input_type -> polarbeam.v1.PushResultsRequest
	5, // 6: polarbeam.v1.AgentService.RenewCert:input_type -> polarbeam.v1.RenewCertRequest
	1, // 7: polarbeam.v1.AgentService.StreamConfig:output_type -> polarbeam.v1.ConfigSnapshot
	4, // 8: polarbeam.v1.AgentService.PushResults:output_type -> polarbeam.v1.PushResultsResponse
	6, // 9: polarbeam.v1.AgentService.RenewCert:output_type -> polarbeam.v1.RenewCertResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_polarbeam_v1_agent_proto_init() }
func file_polarbeam_v1_agent_proto_init() {
	if File_polarbeam_v1_agent_proto != nil {
		return
	}
	file_polarbeam_v1_common_proto_init()
	file_polarbeam_v1_agent_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polarbeam_v1_agent_proto_rawDesc), len(file_polarbeam_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_polarbeam_v1_agent_proto_goTypes,
		DependencyIndexes: file_polarbeam_v1_agent_proto_depIdxs,
		MessageInfos:      file_polarbeam_v1_agent_proto_msgTypes,
	}.Build()
	File_polarbeam_v1_agent_proto = out.File
	file_polarbeam_v1_agent_proto_goTypes = nil
	file_polarbeam_v1_agent_proto_depIdxs = nil
}
