// PolarBEAM wire contract — shared types.
//
// Compatibility rules: this package is consumed by agents that may be
// years old and written in other languages (Windows, ESXi, network gear).
// Fields are only ever added, never renumbered or repurposed. All
// durations/timings are int64 MICROSECONDS with -1 meaning "not measured".

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: polarbeam/v1/common.proto

package polarbeamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProbeType int32

const (
	ProbeType_PROBE_TYPE_UNSPECIFIED ProbeType = 0
	ProbeType_PROBE_TYPE_ICMP        ProbeType = 1
	ProbeType_PROBE_TYPE_TCP         ProbeType = 2
	ProbeType_PROBE_TYPE_TLS         ProbeType = 3
	ProbeType_PROBE_TYPE_HTTP        ProbeType = 4
	ProbeType_PROBE_TYPE_DNS         ProbeType = 5
	ProbeType_PROBE_TYPE_TRACEROUTE  ProbeType = 6
)

// Enum value maps for ProbeType.
var (
	ProbeType_name = map[int32]string{
		0: "PROBE_TYPE_UNSPECIFIED",
		1: "PROBE_TYPE_ICMP",
		2: "PROBE_TYPE_TCP",
		3: "PROBE_TYPE_TLS",
		4: "PROBE_TYPE_HTTP",
		5: "PROBE_TYPE_DNS",
		6: "PROBE_TYPE_TRACEROUTE",
	}
	ProbeType_value = map[string]int32{
		"PROBE_TYPE_UNSPECIFIED": 0,
		"PROBE_TYPE_ICMP":        1,
		"PROBE_TYPE_TCP":         2,
		"PROBE_TYPE_TLS":         3,
		"PROBE_TYPE_HTTP":        4,
		"PROBE_TYPE_DNS":         5,
		"PROBE_TYPE_TRACEROUTE":  6,
	}
)

func (x ProbeType) Enum() *ProbeType {
	p := new(ProbeType)
	*p = x
	return p
}

func (x ProbeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProbeType) Descriptor() protoreflect.EnumDescriptor {
	return file_polarbeam_v1_common_proto_enumTypes[0].Descriptor()
}

func (ProbeType) Type() protoreflect.EnumType {
	return &file_polarbeam_v1_common_proto_enumTypes[0]
}

func (x ProbeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProbeType.Descriptor instead.
func (ProbeType) EnumDescriptor() ([]byte, []int) {
	return file_polarbeam_v1_common_proto_rawDescGZIP(), []int{0}
}

type ProbeStatus int32

const (
	ProbeStatus_PROBE_STATUS_UNSPECIFIED  ProbeStatus = 0
	ProbeStatus_PROBE_STATUS_OK           ProbeStatus = 1
	ProbeStatus_PROBE_STATUS_TIMEOUT      ProbeStatus = 2
	ProbeStatus_PROBE_STATUS_CONN_REFUSED ProbeStatus = 3
	ProbeStatus_PROBE_STATUS_DNS_FAILURE  ProbeStatus = 4
	ProbeStatus_PROBE_STATUS_TLS_FAILURE  ProbeStatus = 5
	ProbeStatus_PROBE_STATUS_ERROR        ProbeStatus = 6
	// The agent does not support this probe type (reported, never silently
	// skipped — the server surfaces it as a config problem).
	ProbeStatus_PROBE_STATUS_UNSUPPORTED ProbeStatus = 7
)

// Enum value maps for ProbeStatus.
var (
	ProbeStatus_name = map[int32]string{
		0: "PROBE_STATUS_UNSPECIFIED",
		1: "PROBE_STATUS_OK",
		2: "PROBE_STATUS_TIMEOUT",
		3: "PROBE_STATUS_CONN_REFUSED",
		4: "PROBE_STATUS_DNS_FAILURE",
		5: "PROBE_STATUS_TLS_FAILURE",
		6: "PROBE_STATUS_ERROR",
		7: "PROBE_STATUS_UNSUPPORTED",
	}
	ProbeStatus_value = map[string]int32{
		"PROBE_STATUS_UNSPECIFIED":  0,
		"PROBE_STATUS_OK":           1,
		"PROBE_STATUS_TIMEOUT":      2,
		"PROBE_STATUS_CONN_REFUSED": 3,
		"PROBE_STATUS_DNS_FAILURE":  4,
		"PROBE_STATUS_TLS_FAILURE":  5,
		"PROBE_STATUS_ERROR":        6,
		"PROBE_STATUS_UNSUPPORTED":  7,
	}
)

func (x ProbeStatus) Enum() *ProbeStatus {
	p := new(ProbeStatus)
	*p = x
	return p
}

func (x ProbeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProbeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_polarbeam_v1_common_proto_enumTypes[1].Descriptor()
}

func (ProbeStatus) Type() protoreflect.EnumType {
	return &file_polarbeam_v1_common_proto_enumTypes[1]
}

func (x ProbeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProbeStatus.Descriptor instead.
func (ProbeStatus) EnumDescriptor() ([]byte, []int) {
	return file_polarbeam_v1_common_proto_rawDescGZIP(), []int{1}
}

type TargetKind int32

const (
	TargetKind_TARGET_KIND_UNSPECIFIED TargetKind = 0
	// A peer polarbeam agent (mesh probe). Direction identity comes from
	// the server-side target row, which resolves to the peer's site.
	TargetKind_TARGET_KIND_AGENT_PEER TargetKind = 1
	// An arbitrary designated endpoint.
	TargetKind_TARGET_KIND_EXTERNAL TargetKind = 2
)

// Enum value maps for TargetKind.
var (
	TargetKind_name = map[int32]string{
		0: "TARGET_KIND_UNSPECIFIED",
		1: "TARGET_KIND_AGENT_PEER",
		2: "TARGET_KIND_EXTERNAL",
	}
	TargetKind_value = map[string]int32{
		"TARGET_KIND_UNSPECIFIED": 0,
		"TARGET_KIND_AGENT_PEER":  1,
		"TARGET_KIND_EXTERNAL":    2,
	}
)

func (x TargetKind) Enum() *TargetKind {
	p := new(TargetKind)
	*p = x
	return p
}

func (x TargetKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetKind) Descriptor() protoreflect.EnumDescriptor {
	return file_polarbeam_v1_common_proto_enumTypes[2].Descriptor()
}

func (TargetKind) Type() protoreflect.EnumType {
	return &file_polarbeam_v1_common_proto_enumTypes[2]
}

func (x TargetKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetKind.Descriptor instead.
func (TargetKind) EnumDescriptor() ([]byte, []int) {
	return file_polarbeam_v1_common_proto_rawDescGZIP(), []int{2}
}

type Target struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  TargetKind             `protobuf:"varint,1,opt,name=kind,proto3,enum=polarbeam.v1.TargetKind" json:"kind,omitempty"`
	// Server-side targets.id — the join key for direction pairing.
	TargetId string `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// host or IP to probe.
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Port    uint32 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	// For HTTP probes: full URL (address/port are derived server-side).
	Url           string `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_polarbeam_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_polarbeam_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_polarbeam_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Target) GetKind() TargetKind {
	if x != nil {
		return x.Kind
	}
	return TargetKind_TARGET_KIND_UNSPECIFIED
}

func (x *Target) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Target) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Target) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Target) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// A single probe assignment. Sent by the server inside ConfigSnapshot.
type ProbeSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable UUID derived deterministically from the probe config or mesh
	// expansion (UUIDv5) — survives config re-pushes unchanged.
	ProbeId  string               `protobuf:"bytes,1,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	Type     ProbeType            `protobuf:"varint,2,opt,name=type,proto3,enum=polarbeam.v1.ProbeType" json:"type,omitempty"`
	Target   *Target              `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Interval *durationpb.Duration `protobuf:"bytes,4,opt,name=interval,proto3" json:"interval,omitempty"`
	Timeout  *durationpb.Duration `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Packets per run for train-based probes (ICMP); 0 = single-shot.
	TrainCount   uint32               `protobuf:"varint,6,opt,name=train_count,json=trainCount,proto3" json:"train_count,omitempty"`
	TrainSpacing *durationpb.Duration `protobuf:"bytes,7,opt,name=train_spacing,json=trainSpacing,proto3" json:"train_spacing,omitempty"`
	// Type-specific parameters, e.g. http.method, http.expect_status,
	// dns.qname, dns.qtype, dns.resolver, tls.sni.
	Params        map[string]string `protobuf:"bytes,8,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeSpec) Reset() {
	*x = ProbeSpec{}
	mi := &file_polarbeam_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeSpec) ProtoMessage() {}

func (x *ProbeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_polarbeam_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeSpec.ProtoReflect.Descriptor instead.
func (*ProbeSpec) Descriptor() ([]byte, []int) {
	return file_polarbeam_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *ProbeSpec) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

func (x *ProbeSpec) GetType() ProbeType {
	if x != nil {
		return x.Type
	}
	return ProbeType_PROBE_TYPE_UNSPECIFIED
}

func (x *ProbeSpec) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ProbeSpec) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *ProbeSpec) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *ProbeSpec) GetTrainCount() uint32 {
	if x != nil {
		return x.TrainCount
	}
	return 0
}

func (x *ProbeSpec) GetTrainSpacing() *durationpb.Duration {
	if x != nil {
		return x.TrainSpacing
	}
	return nil
}

func (x *ProbeSpec) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// Round-trip statistics over a probe train. Microseconds; -1 = not measured.
type RttStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinUs         int64                  `protobuf:"varint,1,opt,name=min_us,json=minUs,proto3" json:"min_us,omitempty"`
	AvgUs         int64                  `protobuf:"varint,2,opt,name=avg_us,json=avgUs,proto3" json:"avg_us,omitempty"`
	MaxUs         int64                  `protobuf:"varint,3,opt,name=max_us,json=maxUs,proto3" json:"max_us,omitempty"`
	StddevUs      int64                  `protobuf:"varint,4,opt,name=stddev_us,json=stddevUs,proto3" json:"stddev_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RttStats) Reset() {
	*x = RttStats{}
	mi := &file_polarbeam_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RttStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RttStats) ProtoMessage() {}

func (x *RttStats) ProtoReflect() protoreflect.Message {
	mi := &file_polarbeam_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RttStats.ProtoReflect.Descriptor instead.
func (*RttStats) Descriptor() ([]byte, []int) {
	return file_polarbeam_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *RttStats) GetMinUs() int64 {
	if x != nil {
		return x.MinUs
	}
	return 0
}

func (x *RttStats) GetAvgUs() int64 {
	if x != nil {
		return x.AvgUs
	}
	return 0
}

func (x *RttStats) GetMaxUs() int64 {
	if x != nil {
		return x.MaxUs
	}
	return 0
}

func (x *RttStats) GetStddevUs() int64 {
	if x != nil {
		return x.StddevUs
	}
	return 0
}

// Phase timings for connection-oriented probes. Microseconds; -1 = not measured.
type Timings struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DnsUs          int64                  `protobuf:"varint,1,opt,name=dns_us,json=dnsUs,proto3" json:"dns_us,omitempty"`
	TcpConnectUs   int64                  `protobuf:"varint,2,opt,name=tcp_connect_us,json=tcpConnectUs,proto3" json:"tcp_connect_us,omitempty"`
	TlsHandshakeUs int64                  `protobuf:"varint,3,opt,name=tls_handshake_us,json=tlsHandshakeUs,proto3" json:"tls_handshake_us,omitempty"`
	TtfbUs         int64                  `protobuf:"varint,4,opt,name=ttfb_us,json=ttfbUs,proto3" json:"ttfb_us,omitempty"`
	TotalUs        int64                  `protobuf:"varint,5,opt,name=total_us,json=totalUs,proto3" json:"total_us,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Timings) Reset() {
	*x = Timings{}
	mi := &file_polarbeam_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timings) ProtoMessage() {}

func (x *Timings) ProtoReflect() protoreflect.Message {
	mi := &file_polarbeam_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timings.ProtoReflect.Descriptor instead.
func (*Timings) Descriptor() ([]byte, []int) {
	return file_polarbeam_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *Timings) GetDnsUs() int64 {
	if x != nil {
		return x.DnsUs
	}
	return 0
}

func (x *Timings) GetTcpConnectUs() int64 {
	if x != nil {
		return x.TcpConnectUs
	}
	return 0
}

func (x *Timings) GetTlsHandshakeUs() int64 {
	if x != nil {
		return x.TlsHandshakeUs
	}
	return 0
}

func (x *Timings) GetTtfbUs() int64 {
	if x != nil {
		return x.TtfbUs
	}
	return 0
}

func (x *Timings) GetTotalUs() int64 {
	if x != nil {
		return x.TotalUs
	}
	return 0
}

type Hop struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ttl   uint32                 `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// Responding addresses at this TTL; empty = silent hop ('*').
	Addrs         []string `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	RttUs         []int64  `protobuf:"varint,3,rep,packed,name=rtt_us,json=rttUs,proto3" json:"rtt_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hop) Reset() {
	*x = Hop{}
	mi := &file_polarbeam_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hop) ProtoMessage() {}

func (x *Hop) ProtoReflect() protoreflect.Message {
	mi := &file_polarbeam_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hop.ProtoReflect.Descriptor instead.
func (*Hop) Descriptor() ([]byte, []int) {
	return file_polarbeam_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *Hop) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Hop) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *Hop) GetRttUs() []int64 {
	if x != nil {
		return x.RttUs
	}
	return nil
}

type TracerouteResult struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Hops        []*Hop                 `protobuf:"bytes,1,rep,name=hops,proto3" json:"hops,omitempty"`
	DestReached bool                   `protobuf:"varint,2,opt,name=dest_reached,json=destReached,proto3" json:"dest_reached,omitempty"`
	// sha256 over the hop address sequence ('*' for silent hops); the server
	// detects path changes by comparing hashes.
	PathHash      []byte `protobuf:"bytes,3,opt,name=path_hash,json=pathHash,proto3" json:"path_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TracerouteResult) Reset() {
	*x = TracerouteResult{}
	mi := &file_polarbeam_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracerouteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracerouteResult) ProtoMessage() {}

func (x *TracerouteResult) ProtoReflect() protoreflect.Message {
	mi := &file_polarbeam_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracerouteResult.ProtoReflect.Descriptor instead.
func (*TracerouteResult) Descriptor() ([]byte, []int) {
	return file_polarbeam_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *TracerouteResult) GetHops() []*Hop {
	if x != nil {
		return x.Hops
	}
	return nil
}

func (x *TracerouteResult) GetDestReached() bool {
	if x != nil {
		return x.DestReached
	}
	return false
}

func (x *TracerouteResult) GetPathHash() []byte {
	if x != nil {
		return x.PathHash
	}
	return nil
}

// One completed probe run.
type ProbeResult struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProbeId   string                 `protobuf:"bytes,1,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	Type      ProbeType              `protobuf:"varint,2,opt,name=type,proto3,enum=polarbeam.v1.ProbeType" json:"type,omitempty"`
	TargetId  string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Status    ProbeStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=polarbeam.v1.ProbeStatus" json:"status,omitempty"`
	Error     string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	// Train accounting: loss = (sent - received) / sent.
	Sent     uint32    `protobuf:"varint,7,opt,name=sent,proto3" json:"sent,omitempty"`
	Received uint32    `protobuf:"varint,8,opt,name=received,proto3" json:"received,omitempty"`
	Rtt      *RttStats `protobuf:"bytes,9,opt,name=rtt,proto3" json:"rtt,omitempty"`
	// RFC 3550 smoothed interarrival jitter, microseconds; -1 = not measured.
	JitterUs      int64             `protobuf:"varint,10,opt,name=jitter_us,json=jitterUs,proto3" json:"jitter_us,omitempty"`
	Timings       *Timings          `protobuf:"bytes,11,opt,name=timings,proto3" json:"timings,omitempty"`
	Traceroute    *TracerouteResult `protobuf:"bytes,12,opt,name=traceroute,proto3" json:"traceroute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResult) Reset() {
	*x = ProbeResult{}
	mi := &file_polarbeam_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResult) ProtoMessage() {}

func (x *ProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_polarbeam_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResult.ProtoReflect.Descriptor instead.
func (*ProbeResult) Descriptor() ([]byte, []int) {
	return file_polarbeam_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *ProbeResult) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

func (x *ProbeResult) GetType() ProbeType {
	if x != nil {
		return x.Type
	}
	return ProbeType_PROBE_TYPE_UNSPECIFIED
}

func (x *ProbeResult) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ProbeResult) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ProbeResult) GetStatus() ProbeStatus {
	if x != nil {
		return x.Status
	}
	return ProbeStatus_PROBE_STATUS_UNSPECIFIED
}

func (x *ProbeResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ProbeResult) GetSent() uint32 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *ProbeResult) GetReceived() uint32 {
	if x != nil {
		return x.Received
	}
	return 0
}

func (x *ProbeResult) GetRtt() *RttStats {
	if x != nil {
		return x.Rtt
	}
	return nil
}

func (x *ProbeResult) GetJitterUs() int64 {
	if x != nil {
		return x.JitterUs
	}
	return 0
}

func (x *ProbeResult) GetTimings() *Timings {
	if x != nil {
		return x.Timings
	}
	return nil
}

func (x *ProbeResult) GetTraceroute() *TracerouteResult {
	if x != nil {
		return x.Traceroute
	}
	return nil
}

var File_polarbeam_v1_common_proto protoreflect.FileDescriptor

const file_polarbeam_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x19polarbeam/v1/common.proto\x12\fpolarbeam.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x01\n" +
	"\x06Target\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.polarbeam.v1.TargetKindR\x04kind\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\"\xc6\x03\n" +
	"\tProbeSpec\x12\x19\n" +
	"\bprobe_id\x18\x01 \x01(\tR\aprobeId\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.polarbeam.v1.ProbeTypeR\x04type\x12,\n" +
	"\x06target\x18\x03 \x01(\v2\x14.polarbeam.v1.TargetR\x06target\x125\n" +
	"\binterval\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\binterval\x123\n" +
	"\atimeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1f\n" +
	"\vtrain_count\x18\x06 \x01(\rR\n" +
	"trainCount\x12>\n" +
	"\rtrain_spacing\x18\a \x01(\v2\x19.google.protobuf.DurationR\ftrainSpacing\x12;\n" +
	"\x06params\x18\b \x03(\v2#.polarbeam.v1.ProbeSpec.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\bRttStats\x12\x15\n" +
	"\x06min_us\x18\x01 \x01(\x03R\x05minUs\x12\x15\n" +
	"\x06avg_us\x18\x02 \x01(\x03R\x05avgUs\x12\x15\n" +
	"\x06max_us\x18\x03 \x01(\x03R\x05maxUs\x12\x1b\n" +
	"\tstddev_us\x18\x04 \x01(\x03R\bstddevUs\"\xa4\x01\n" +
	"\aTimings\x12\x15\n" +
	"\x06dns_us\x18\x01 \x01(\x03R\x05dnsUs\x12$\n" +
	"\x0etcp_connect_us\x18\x02 \x01(\x03R\ftcpConnectUs\x12(\n" +
	"\x10tls_handshake_us\x18\x03 \x01(\x03R\x0etlsHandshakeUs\x12\x17\n" +
	"\attfb_us\x18\x04 \x01(\x03R\x06ttfbUs\x12\x19\n" +
	"\btotal_us\x18\x05 \x01(\x03R\atotalUs\"D\n" +
	"\x03Hop\x12\x10\n" +
	"\x03ttl\x18\x01 \x01(\rR\x03ttl\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\tR\x05addrs\x12\x15\n" +
	"\x06rtt_us\x18\x03 \x03(\x03R\x05rttUs\"y\n" +
	"\x10TracerouteResult\x12%\n" +
	"\x04hops\x18\x01 \x03(\v2\x11.polarbeam.v1.HopR\x04hops\x12!\n" +
	"\fdest_reached\x18\x02 \x01(\bR\vdestReached\x12\x1b\n" +
	"\tpath_hash\x18\x03 \x01(\fR\bpathHash\"\xde\x03\n" +
	"\vProbeResult\x12\x19\n" +
	"\bprobe_id\x18\x01 \x01(\tR\aprobeId\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.polarbeam.v1.ProbeTypeR\x04type\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x121\n" +
	"\x06status\x18\x05 \x01(\x0e2\x19.polarbeam.v1.ProbeStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x12\n" +
	"\x04sent\x18\a \x01(\rR\x04sent\x12\x1a\n" +
	"\breceived\x18\b \x01(\rR\breceived\x12(\n" +
	"\x03rtt\x18\t \x01(\v2\x16.polarbeam.v1.RttStatsR\x03rtt\x12\x1b\n" +
	"\tjitter_us\x18\n" +
	" \x01(\x03R\bjitterUs\x12/\n" +
	"\atimings\x18\v \x01(\v2\x15.polarbeam.v1.TimingsR\atimings\x12>\n" +
	"\n" +
	"traceroute\x18\f \x01(\v2\x1e.polarbeam.v1.TracerouteResultR\n" +
	"traceroute*\xa8\x01\n" +
	"\tProbeType\x12\x1a\n" +
	"\x16PROBE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPROBE_TYPE_ICMP\x10\x01\x12\x12\n" +
	"\x0ePROBE_TYPE_TCP\x10\x02\x12\x12\n" +
	"\x0ePROBE_TYPE_TLS\x10\x03\x12\x13\n" +
	"\x0fPROBE_TYPE_HTTP\x10\x04\x12\x12\n" +
	"\x0ePROBE_TYPE_DNS\x10\x05\x12\x19\n" +
	"\x15PROBE_TYPE_TRACEROUTE\x10\x06*\xeb\x01\n" +
	"\vProbeStatus\x12\x1c\n" +
	"\x18PROBE_STATUS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPROBE_STATUS_OK\x10\x01\x12\x18\n" +
	"\x14PROBE_STATUS_TIMEOUT\x10\x02\x12\x1d\n" +
	"\x19PROBE_STATUS_CONN_REFUSED\x10\x03\x12\x1c\n" +
	"\x18PROBE_STATUS_DNS_FAILURE\x10\x04\x12\x1c\n" +
	"\x18PROBE_STATUS_TLS_FAILURE\x10\x05\x12\x16\n" +
	"\x12PROBE_STATUS_ERROR\x10\x06\x12\x1c\n" +
	"\x18PROBE_STATUS_UNSUPPORTED\x10\a*_\n" +
	"\n" +
	"TargetKind\x12\x1b\n" +
	"\x17TARGET_KIND_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TARGET_KIND_AGENT_PEER\x10\x01\x12\x18\n" +
	"\x14TARGET_KIND_EXTERNAL\x10\x02B9Z7github.com/devalexllc/polarbeam/internal/pb/polarbeamv1b\x06proto3"

var (
	file_polarbeam_v1_common_proto_rawDescOnce sync.Once
	file_polarbeam_v1_common_proto_rawDescData []byte
)

func file_polarbeam_v1_common_proto_rawDescGZIP() []byte {
	file_polarbeam_v1_common_proto_rawDescOnce.Do(func() {
		file_polarbeam_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polarbeam_v1_common_proto_rawDesc), len(file_polarbeam_v1_common_proto_rawDesc)))
	})
	return file_polarbeam_v1_common_proto_rawDescData
}

var file_polarbeam_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_polarbeam_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_polarbeam_v1_common_proto_goTypes = []any{
	(ProbeType)(0),                // 0: polarbeam.v1.ProbeType
	(ProbeStatus)(0),              // 1: polarbeam.v1.ProbeStatus
	(TargetKind)(0),               // 2: polarbeam.v1.TargetKind
	(*Target)(nil),                // 3: polarbeam.v1.Target
	(*ProbeSpec)(nil),             // 4: polarbeam.v1.ProbeSpec
	(*RttStats)(nil),              // 5: polarbeam.v1.RttStats
	(*Timings)(nil),               // 6: polarbeam.v1.Timings
	(*Hop)(nil),                   // 7: polarbeam.v1.Hop
	(*TracerouteResult)(nil),      // 8: polarbeam.v1.TracerouteResult
	(*ProbeResult)(nil),           // 9: polarbeam.v1.ProbeResult
	nil,                           // 10: polarbeam.v1.ProbeSpec.ParamsEntry
	(*durationpb.Duration)(nil),   // 11: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_polarbeam_v1_common_proto_depIdxs = []int32{
	2,  // 0: polarbeam.v1.Target.kind:type_name -> polarbeam.v1.TargetKind
	0,  // 1: polarbeam.v1.ProbeSpec.type:type_name -> polarbeam.v1.ProbeType
	3,  // 2: polarbeam.v1.ProbeSpec.target:type_name -> polarbeam.v1.Target
	11, // 3: polarbeam.v1.ProbeSpec.interval:type_name -> google.protobuf.Duration
	11, // 4: polarbeam.v1.ProbeSpec.timeout:type_name -> google.protobuf.Duration
	11, // 5: polarbeam.v1.ProbeSpec.train_spacing:type_name -> google.protobuf.Duration
	10, // 6: polarbeam.v1.ProbeSpec.params:type_name -> polarbeam.v1.ProbeSpec.ParamsEntry
	7,  // 7: polarbeam.v1.TracerouteResult.hops:type_name -> polarbeam.v1.Hop
	0,  // 8: polarbeam.v1.ProbeResult.type:type_name -> polarbeam.v1.ProbeType
	12, // 9: polarbeam.v1.ProbeResult.started_at:type_name -> google.protobuf.Timestamp
	1,  // 10: polarbeam.v1.ProbeResult.status:type_name -> polarbeam.v1.ProbeStatus
	5,  // 11: polarbeam.v1.ProbeResult.rtt:type_name -> polarbeam.v1.RttStats
	6,  // 12: polarbeam.v1.ProbeResult.timings:type_name -> polarbeam.v1.Timings
	8,  // 13: polarbeam.v1.ProbeResult.traceroute:type_name -> polarbeam.v1.TracerouteResult
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_polarbeam_v1_common_proto_init() }
func file_polarbeam_v1_common_proto_init() {
	if File_polarbeam_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polarbeam_v1_common_proto_rawDesc), len(file_polarbeam_v1_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_polarbeam_v1_common_proto_goTypes,
		DependencyIndexes: file_polarbeam_v1_common_proto_depIdxs,
		EnumInfos:         file_polarbeam_v1_common_proto_enumTypes,
		MessageInfos:      file_polarbeam_v1_common_proto_msgTypes,
	}.Build()
	File_polarbeam_v1_common_proto = out.File
	file_polarbeam_v1_common_proto_goTypes = nil
	file_polarbeam_v1_common_proto_depIdxs = nil
}
