// Agent enrollment: join token + CSR in, signed client certificate out.
// This is the only RPC served WITHOUT a client certificate (server-TLS only);
// the one-time join token is the authentication.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: polarbeam/v1/enrollment.proto

package polarbeamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One-time token issued by `polarbeam-server token create` ("<id>.<secret>").
	JoinToken string `protobuf:"bytes,1,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	// PKCS#10 certificate signing request, DER. The private key never leaves
	// the agent.
	CsrDer       []byte `protobuf:"bytes,2,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`
	Hostname     string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	AgentVersion string `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// Address peers should use to probe this agent (defaults to the observed
	// source address if empty; must be set when the agent is behind NAT).
	ProbeAddress  string `protobuf:"bytes,5,opt,name=probe_address,json=probeAddress,proto3" json:"probe_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_polarbeam_v1_enrollment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polarbeam_v1_enrollment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_polarbeam_v1_enrollment_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

func (x *EnrollRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

func (x *EnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EnrollRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *EnrollRequest) GetProbeAddress() string {
	if x != nil {
		return x.ProbeAddress
	}
	return ""
}

type EnrollResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned identity; also embedded in the certificate URI SAN
	// (polarbeam://agent/<uuid>).
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Signed client certificate, DER.
	CertDer []byte `protobuf:"bytes,2,opt,name=cert_der,json=certDer,proto3" json:"cert_der,omitempty"`
	// CA bundle the agent must trust for the mTLS channel, DER (may contain
	// multiple certificates, concatenated).
	CaBundleDer   []byte                 `protobuf:"bytes,3,opt,name=ca_bundle_der,json=caBundleDer,proto3" json:"ca_bundle_der,omitempty"`
	NotAfter      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_polarbeam_v1_enrollment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_polarbeam_v1_enrollment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_polarbeam_v1_enrollment_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EnrollResponse) GetCertDer() []byte {
	if x != nil {
		return x.CertDer
	}
	return nil
}

func (x *EnrollResponse) GetCaBundleDer() []byte {
	if x != nil {
		return x.CaBundleDer
	}
	return nil
}

func (x *EnrollResponse) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

var File_polarbeam_v1_enrollment_proto protoreflect.FileDescriptor

const file_polarbeam_v1_enrollment_proto_rawDesc = "" +
	"\n" +
	"\x1dpolarbeam/v1/enrollment.proto\x12\fpolarbeam.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xad\x01\n" +
	"\rEnrollRequest\x12\x1d\n" +
	"\n" +
	"join_token\x18\x01 \x01(\tR\tjoinToken\x12\x17\n" +
	"\acsr_der\x18\x02 \x01(\fR\x06csrDer\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x12#\n" +
	"\rprobe_address\x18\x05 \x01(\tR\fprobeAddress\"\xa3\x01\n" +
	"\x0eEnrollResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x19\n" +
	"\bcert_der\x18\x02 \x01(\fR\acertDer\x12\"\n" +
	"\rca_bundle_der\x18\x03 \x01(\fR\vcaBundleDer\x127\n" +
	"\tnot_after\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter2X\n" +
	"\x11EnrollmentService\x12C\n" +
	"\x06Enroll\x12\x1b.polarbeam.v1.EnrollRequest\x1a\x1c.polarbeam.v1.EnrollResponseB9Z7github.com/devalexllc/polarbeam/internal/pb/polarbeamv1b\x06proto3"

var (
	file_polarbeam_v1_enrollment_proto_rawDescOnce sync.Once
	file_polarbeam_v1_enrollment_proto_rawDescData []byte
)

func file_polarbeam_v1_enrollment_proto_rawDescGZIP() []byte {
	file_polarbeam_v1_enrollment_proto_rawDescOnce.Do(func() {
		file_polarbeam_v1_enrollment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_polarbeam_v1_enrollment_proto_rawDesc), len(file_polarbeam_v1_enrollment_proto_rawDesc)))
	})
	return file_polarbeam_v1_enrollment_proto_rawDescData
}

var file_polarbeam_v1_enrollment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_polarbeam_v1_enrollment_proto_goTypes = []any{
	(*EnrollRequest)(nil),         // 0: polarbeam.v1.EnrollRequest
	(*EnrollResponse)(nil),        // 1: polarbeam.v1.EnrollResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_polarbeam_v1_enrollment_proto_depIdxs = []int32{
	2, // 0: polarbeam.v1.EnrollResponse.not_after:type_name -> google.protobuf.Timestamp
	0, // 1: polarbeam.v1.EnrollmentService.Enroll:input_type -> polarbeam.v1.EnrollRequest
	1, // 2: polarbeam.v1.EnrollmentService.Enroll:output_type -> polarbeam.v1.EnrollResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_polarbeam_v1_enrollment_proto_init() }
func file_polarbeam_v1_enrollment_proto_init() {
	if File_polarbeam_v1_enrollment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_polarbeam_v1_enrollment_proto_rawDesc), len(file_polarbeam_v1_enrollment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_polarbeam_v1_enrollment_proto_goTypes,
		DependencyIndexes: file_polarbeam_v1_enrollment_proto_depIdxs,
		MessageInfos:      file_polarbeam_v1_enrollment_proto_msgTypes,
	}.Build()
	File_polarbeam_v1_enrollment_proto = out.File
	file_polarbeam_v1_enrollment_proto_goTypes = nil
	file_polarbeam_v1_enrollment_proto_depIdxs = nil
}
